"""foreign keys determined

Revision ID: 5281ce2bc785
Revises: cfa98483ffe4
Create Date: 2024-01-03 18:09:50.833599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5281ce2bc785'
down_revision: Union[str, None] = 'cfa98483ffe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###
