"""Initial migration

Revision ID: cfa98483ffe4
Revises: 
Create Date: 2024-01-03 16:57:19.014465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa98483ffe4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('user_key', sa.Integer(), primary_key=True),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('created_ts', sa.TIMESTAMP(), nullable=False),
        sa.Column('last_updated_ts', sa.TIMESTAMP(), nullable=False),
        sa.Column('telegram_key', sa.Integer(), unique=True),
        sa.Column('location_lat', sa.Float()),
        sa.Column('location_lon', sa.Float()),
        sa.Column('city', sa.String())
    )
    op.create_table('books',
        sa.Column('book_key', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('author', sa.String(), nullable=False),
        sa.Column('description', sa.String()),
        sa.Column('user_key', sa.Integer(), sa.ForeignKey('users.user_key')),
        sa.Column('created_ts', sa.TIMESTAMP(), nullable=False),
        sa.Column('last_updated_ts', sa.TIMESTAMP(), nullable=False),
        sa.Column('is_available', sa.Boolean(), default=True)
    )
    op.create_table('bookings',
        sa.Column('booking_key', sa.Integer(), primary_key=True),
        sa.Column('book_key', sa.Integer(), sa.ForeignKey('books.book_key')),
        sa.Column('from_user_key', sa.Integer(), sa.ForeignKey('users.user_key')),
        sa.Column('to_user_key', sa.Integer(), sa.ForeignKey('users.user_key')),
        sa.Column('borrow_ts', sa.DateTime(), default=sa.func.now()),
        sa.Column('return_ts', sa.DateTime()),
        sa.Column('status', sa.String(), default='draft'),
        sa.Column('created_ts', sa.TIMESTAMP(), nullable=False),
        sa.Column('last_updated_ts', sa.TIMESTAMP(), nullable=False)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('books')
    op.drop_table('users')
    # ### end Alembic commands ###